version: '3.8'

services:
  web-alumni:
    image: kevinio/web-alumni:latest
    container_name: web-alumni-prod
    restart: unless-stopped
    platform: linux/arm64
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - web-alumni-cache:/app/.next/cache
      - web-alumni-data:/app/data

volumes:
  web-alumni-cache:
    driver: local
  web-alumni-data:
    driver: local